// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYY_hzk_2EbyaE-f5UxALxmJRB1EpBKOw',
    appId: '1:106806858052:web:465932aa3a3683b1144711',
    messagingSenderId: '106806858052',
    projectId: 'ecommerceapp-c3312',
    authDomain: 'ecommerceapp-c3312.firebaseapp.com',
    storageBucket: 'ecommerceapp-c3312.appspot.com',
    measurementId: 'G-N322R1EDR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRS7jKhisQQYaZY6UPFVQoGlXVmrDIz34',
    appId: '1:106806858052:android:25b052b4ecba2e05144711',
    messagingSenderId: '106806858052',
    projectId: 'ecommerceapp-c3312',
    storageBucket: 'ecommerceapp-c3312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tybc2AX6e9HTmVRqFx5zkooGIcWtFT8',
    appId: '1:106806858052:ios:285b539d93693b44144711',
    messagingSenderId: '106806858052',
    projectId: 'ecommerceapp-c3312',
    storageBucket: 'ecommerceapp-c3312.appspot.com',
    androidClientId: '106806858052-6tecjgom85am09rmlo9fd8ns76pglv7e.apps.googleusercontent.com',
    iosClientId: '106806858052-lhqln3ic8ejhj5pa2lod45o2qd0ti9pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
